-- ============================================
-- Script de création de la table FOURNISSEURS
-- Projet: FIL D'OR - Gestion des Fournisseurs
-- ============================================

-- Suppression de la table si elle existe
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FOURNISSEURS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Suppression de la séquence si elle existe
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FOURNISSEUR';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

-- Création de la table FOURNISSEURS
CREATE TABLE FOURNISSEURS (
    ID_FOURNISSEUR NUMBER PRIMARY KEY,
    NOM_FOURNISSEUR VARCHAR2(100) NOT NULL,
    TYPE_CUIR VARCHAR2(50) NOT NULL,  -- 'Cuir Vachette', 'Cuir Agneau', 'Cuir Veau'
    PRIX_PAR_M2 NUMBER(10,2) NOT NULL,
    QUALITE VARCHAR2(50) NOT NULL,    -- 'A (Premium)', 'B (Standard)', 'C (Économique)'
    DELAI_JOURS NUMBER NOT NULL,
    STOCK_DISPO NUMBER(10,2) NOT NULL,
    EMAIL VARCHAR2(100),
    TELEPHONE VARCHAR2(20),
    ADRESSE VARCHAR2(200),
    ACTIF CHAR(1) DEFAULT '1' CHECK (ACTIF IN ('0', '1')),
    DATE_CREATION DATE DEFAULT SYSDATE,
    DATE_MODIFICATION DATE DEFAULT SYSDATE
);

-- Création de la séquence pour l'ID
CREATE SEQUENCE SEQ_FOURNISSEUR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Insertion des données initiales pour Cuir Vachette
INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'TanLeather SA', 'Cuir Vachette', 45.00, 'A (Premium)', 5, 500.00, 'contact@tanleather.tn', '+216 71 100 201', 'Zone Industrielle, Tunis', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Cuir Elite', 'Cuir Vachette', 38.00, 'B (Standard)', 7, 300.00, 'info@cuirelite.tn', '+216 71 200 302', 'Sfax, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'MegaCuir', 'Cuir Vachette', 32.00, 'C (Économique)', 10, 1000.00, 'contact@megacuir.tn', '+216 71 300 403', 'Sousse, Tunisie', '1');

-- Insertion des données pour Cuir Agneau
INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'SoftHide Pro', 'Cuir Agneau', 52.00, 'A (Premium)', 4, 420.00, 'contact@softhide.tn', '+216 71 400 504', 'Ariana, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Agneau Plus', 'Cuir Agneau', 44.00, 'B+ (Standard)', 6, 280.00, 'info@agneauplus.tn', '+216 71 500 605', 'Monastir, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Cuir Sud', 'Cuir Agneau', 36.00, 'C (Économique)', 9, 900.00, 'contact@cuirsud.tn', '+216 71 600 706', 'Gabès, Tunisie', '1');

-- Insertion des données pour Cuir Veau
INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Veau Prestige', 'Cuir Veau', 49.00, 'A (Premium)', 5, 380.00, 'contact@veauprestige.tn', '+216 71 700 807', 'Bizerte, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Elite Veau', 'Cuir Veau', 41.00, 'B (Standard)', 7, 260.00, 'info@eliteveau.tn', '+216 71 800 908', 'Nabeul, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Market Cuir', 'Cuir Veau', 34.00, 'C (Économique)', 11, 1100.00, 'contact@marketcuir.tn', '+216 71 900 109', 'Kairouan, Tunisie', '1');

COMMIT;

-- Affichage des données insérées
SELECT * FROM FOURNISSEURS ORDER BY TYPE_CUIR, PRIX_PAR_M2 DESC;
