-- ============================================
-- Script de création de la table MATIERES_PREMIERES
-- Projet: FIL D'OR - Gestion des Matières Premières
-- ============================================

-- Suppression de la table si elle existe
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MATIERES_PREMIERES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Suppression de la séquence si elle existe
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAT';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN
         RAISE;
      END IF;
END;
/

-- Création de la table MATIERES_PREMIERES
CREATE TABLE MATIERES_PREMIERES (
    ID_STOCK_MP NUMBER PRIMARY KEY,
    CODE_MP VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORIE_MP VARCHAR2(50) NOT NULL,
    NUM_LOT VARCHAR2(50) NOT NULL,
    ETAT_MP VARCHAR2(20) NOT NULL,
    COULEUR VARCHAR2(50) NOT NULL,
    QUANTITE NUMBER(10,2) NOT NULL CHECK (QUANTITE > 0),
    TYPE_STOCKAGE VARCHAR2(20) NOT NULL,
    QUALITE VARCHAR2(10) NOT NULL,
    DATE_CREATION DATE DEFAULT SYSDATE,
    DATE_MODIFICATION DATE DEFAULT SYSDATE
);

-- Création de la séquence pour l'ID
CREATE SEQUENCE SEQ_MAT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Insertion de données de test
INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'CUIR-2024-001', 'Cuir', 'LOT-2024-A', 'BRUT', 'Marron', 150.50, 'Sec', 'A');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'CUIR-2024-002', 'Cuir', 'LOT-2024-B', 'TEINT', 'Noir', 200.00, 'Sec', 'A');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'FIL-2024-001', 'Fil', 'LOT-2024-C', 'BRUT', 'Blanc', 50.00, 'Sec', 'B');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'CUIR-2024-003', 'Cuir', 'LOT-2024-D', 'TEINT', 'Beige', 180.75, 'Froid', 'A');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'FIL-2024-002', 'Fil', 'LOT-2024-E', 'BRUT', 'Noir', 75.25, 'Sec', 'B');

COMMIT;

-- Affichage des données insérées
SELECT * FROM MATIERES_PREMIERES ORDER BY ID_STOCK_MP;

-- Vérification de la séquence
SELECT SEQ_MAT.CURRVAL FROM DUAL;
