-- ============================================
-- Script d'intégration complète - Matières Premières
-- Projet: FIL D'OR - Gestion Matières Premières + Ravitaillement
-- Date: 2026-05-05
-- ============================================

SET SERVEROUTPUT ON;

PROMPT ========================================
PROMPT INTÉGRATION COMPLÈTE MATIÈRES PREMIÈRES
PROMPT ========================================

-- =============================================
-- 1. TABLE MATIERES_PREMIERES
-- =============================================
PROMPT;
PROMPT [1/5] Création table MATIERES_PREMIERES...

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MATIERES_PREMIERES CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('✓ Table MATIERES_PREMIERES supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      ELSE DBMS_OUTPUT.PUT_LINE('→ Table MATIERES_PREMIERES n''existe pas');
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MAT';
   DBMS_OUTPUT.PUT_LINE('✓ Séquence SEQ_MAT supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE;
      ELSE DBMS_OUTPUT.PUT_LINE('→ Séquence SEQ_MAT n''existe pas');
      END IF;
END;
/

CREATE TABLE MATIERES_PREMIERES (
    ID_STOCK_MP NUMBER PRIMARY KEY,
    CODE_MP VARCHAR2(50) NOT NULL UNIQUE,
    CATEGORIE_MP VARCHAR2(50) NOT NULL,
    NUM_LOT VARCHAR2(50) NOT NULL,
    ETAT_MP VARCHAR2(20) NOT NULL,
    COULEUR VARCHAR2(50) NOT NULL,
    QUANTITE NUMBER(10,2) NOT NULL CHECK (QUANTITE > 0),
    TYPE_STOCKAGE VARCHAR2(20) NOT NULL,
    QUALITE VARCHAR2(10) NOT NULL,
    DATE_CREATION DATE DEFAULT SYSDATE,
    DATE_MODIFICATION DATE DEFAULT SYSDATE,
    CONSTRAINT CHK_ETAT_MP CHECK (ETAT_MP IN ('BRUT', 'TEINT', 'TRAITE')),
    CONSTRAINT CHK_TYPE_STOCKAGE CHECK (TYPE_STOCKAGE IN ('Sec', 'Froid', 'Humide')),
    CONSTRAINT CHK_QUALITE_MP CHECK (QUALITE IN ('A', 'B', 'C'))
);

CREATE SEQUENCE SEQ_MAT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE MATIERES_PREMIERES IS 'Gestion des matières premières (cuir, fil, etc.)';
COMMENT ON COLUMN MATIERES_PREMIERES.CODE_MP IS 'Code unique format: XXX-YYYY-NNN';
COMMENT ON COLUMN MATIERES_PREMIERES.CATEGORIE_MP IS 'Catégorie: Cuir, Fil, etc.';
COMMENT ON COLUMN MATIERES_PREMIERES.QUALITE IS 'A=Premium, B=Standard, C=Économique';

-- Données de test
INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'CUIR-2024-001', 'Cuir', 'LOT-2024-A', 'BRUT', 'Marron', 150.50, 'Sec', 'A');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'CUIR-2024-002', 'Cuir', 'LOT-2024-B', 'TEINT', 'Noir', 200.00, 'Sec', 'A');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'FIL-2024-001', 'Fil', 'LOT-2024-C', 'BRUT', 'Blanc', 50.00, 'Sec', 'B');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'CUIR-2024-003', 'Cuir', 'LOT-2024-D', 'TEINT', 'Beige', 180.75, 'Froid', 'A');

INSERT INTO MATIERES_PREMIERES (ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP, COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE)
VALUES (SEQ_MAT.NEXTVAL, 'FIL-2024-002', 'Fil', 'LOT-2024-E', 'BRUT', 'Noir', 75.25, 'Sec', 'B');

COMMIT;
PROMPT ✓ Table MATIERES_PREMIERES créée avec 5 enregistrements

-- =============================================
-- 2. TABLE FOURNISSEURS
-- =============================================
PROMPT;
PROMPT [2/5] Création table FOURNISSEURS...

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FOURNISSEURS CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('✓ Table FOURNISSEURS supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      ELSE DBMS_OUTPUT.PUT_LINE('→ Table FOURNISSEURS n''existe pas');
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FOURNISSEUR';
   DBMS_OUTPUT.PUT_LINE('✓ Séquence SEQ_FOURNISSEUR supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE;
      ELSE DBMS_OUTPUT.PUT_LINE('→ Séquence SEQ_FOURNISSEUR n''existe pas');
      END IF;
END;
/

CREATE TABLE FOURNISSEURS (
    ID_FOURNISSEUR NUMBER PRIMARY KEY,
    NOM_FOURNISSEUR VARCHAR2(100) NOT NULL,
    TYPE_CUIR VARCHAR2(50) NOT NULL,
    PRIX_PAR_M2 NUMBER(10,2) NOT NULL CHECK (PRIX_PAR_M2 > 0),
    QUALITE VARCHAR2(50) NOT NULL,
    DELAI_JOURS NUMBER NOT NULL CHECK (DELAI_JOURS >= 0),
    STOCK_DISPO NUMBER(10,2) NOT NULL CHECK (STOCK_DISPO >= 0),
    EMAIL VARCHAR2(100),
    TELEPHONE VARCHAR2(20),
    ADRESSE VARCHAR2(200),
    ACTIF CHAR(1) DEFAULT '1' CHECK (ACTIF IN ('0', '1')),
    DATE_CREATION DATE DEFAULT SYSDATE,
    DATE_MODIFICATION DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_FOURNISSEUR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE FOURNISSEURS IS 'Fournisseurs de matières premières';
COMMENT ON COLUMN FOURNISSEURS.TYPE_CUIR IS 'Type: Cuir Vachette, Cuir Agneau, Cuir Veau';
COMMENT ON COLUMN FOURNISSEURS.QUALITE IS 'A (Premium), B (Standard), C (Économique)';

-- Fournisseurs Cuir Vachette
INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'TanLeather SA', 'Cuir Vachette', 45.00, 'A (Premium)', 5, 500.00, 'contact@tanleather.tn', '+216 71 100 201', 'Zone Industrielle, Tunis', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Cuir Elite', 'Cuir Vachette', 38.00, 'B (Standard)', 7, 300.00, 'info@cuirelite.tn', '+216 71 200 302', 'Sfax, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'MegaCuir', 'Cuir Vachette', 32.00, 'C (Économique)', 10, 1000.00, 'contact@megacuir.tn', '+216 71 300 403', 'Sousse, Tunisie', '1');

-- Fournisseurs Cuir Agneau
INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'SoftHide Pro', 'Cuir Agneau', 52.00, 'A (Premium)', 4, 420.00, 'contact@softhide.tn', '+216 71 400 504', 'Ariana, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Agneau Plus', 'Cuir Agneau', 44.00, 'B+ (Standard)', 6, 280.00, 'info@agneauplus.tn', '+216 71 500 605', 'Monastir, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Cuir Sud', 'Cuir Agneau', 36.00, 'C (Économique)', 9, 900.00, 'contact@cuirsud.tn', '+216 71 600 706', 'Gabès, Tunisie', '1');

-- Fournisseurs Cuir Veau
INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Veau Prestige', 'Cuir Veau', 49.00, 'A (Premium)', 5, 380.00, 'contact@veauprestige.tn', '+216 71 700 807', 'Bizerte, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Elite Veau', 'Cuir Veau', 41.00, 'B (Standard)', 7, 260.00, 'info@eliteveau.tn', '+216 71 800 908', 'Nabeul, Tunisie', '1');

INSERT INTO FOURNISSEURS (ID_FOURNISSEUR, NOM_FOURNISSEUR, TYPE_CUIR, PRIX_PAR_M2, QUALITE, DELAI_JOURS, STOCK_DISPO, EMAIL, TELEPHONE, ADRESSE, ACTIF)
VALUES (SEQ_FOURNISSEUR.NEXTVAL, 'Market Cuir', 'Cuir Veau', 34.00, 'C (Économique)', 11, 1100.00, 'contact@marketcuir.tn', '+216 71 900 109', 'Kairouan, Tunisie', '1');

COMMIT;
PROMPT ✓ Table FOURNISSEURS créée avec 9 fournisseurs

-- =============================================
-- 3. TABLE STOCK_MP
-- =============================================
PROMPT;
PROMPT [3/5] Création table STOCK_MP...

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE STOCK_MP CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('✓ Table STOCK_MP supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      ELSE DBMS_OUTPUT.PUT_LINE('→ Table STOCK_MP n''existe pas');
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STOCK_MP';
   DBMS_OUTPUT.PUT_LINE('✓ Séquence SEQ_STOCK_MP supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -2289 THEN RAISE;
      ELSE DBMS_OUTPUT.PUT_LINE('→ Séquence SEQ_STOCK_MP n''existe pas');
      END IF;
END;
/

CREATE TABLE STOCK_MP (
    ID_STOCK NUMBER PRIMARY KEY,
    CATEGORIE_MP VARCHAR2(50) NOT NULL,
    QUANTITE NUMBER(10,2) NOT NULL CHECK (QUANTITE >= 0),
    DATE_MAJ DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_STOCK_MP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMENT ON TABLE STOCK_MP IS 'Vue agrégée du stock par catégorie';

INSERT INTO STOCK_MP (ID_STOCK, CATEGORIE_MP, QUANTITE)
VALUES (SEQ_STOCK_MP.NEXTVAL, 'CUIR VACHETTE', 500.00);

INSERT INTO STOCK_MP (ID_STOCK, CATEGORIE_MP, QUANTITE)
VALUES (SEQ_STOCK_MP.NEXTVAL, 'CUIR AGNEAU', 420.00);

INSERT INTO STOCK_MP (ID_STOCK, CATEGORIE_MP, QUANTITE)
VALUES (SEQ_STOCK_MP.NEXTVAL, 'CUIR VEAU', 380.00);

INSERT INTO STOCK_MP (ID_STOCK, CATEGORIE_MP, QUANTITE)
VALUES (SEQ_STOCK_MP.NEXTVAL, 'FIL', 125.25);

COMMIT;
PROMPT ✓ Table STOCK_MP créée avec 4 catégories

-- =============================================
-- 4. TABLE RAVITAILLEMENT_LOG
-- =============================================
PROMPT;
PROMPT [4/5] Création table RAVITAILLEMENT_LOG...

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAVITAILLEMENT_LOG CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('✓ Table RAVITAILLEMENT_LOG supprimée');
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE;
      ELSE DBMS_OUTPUT.PUT_LINE('→ Table RAVITAILLEMENT_LOG n''existe pas');
      END IF;
END;
/

CREATE TABLE RAVITAILLEMENT_LOG (
    LOG_ID VARCHAR2(40) PRIMARY KEY,
    DATE_LOG TIMESTAMP DEFAULT SYSTIMESTAMP,
    MATIERE VARCHAR2(100) NOT NULL,
    FOURNISSEUR VARCHAR2(100) NOT NULL,
    SCORE_GLOBAL NUMBER(5,2),
    QUANTITE_COMMANDE NUMBER(10,2) NOT NULL,
    BUDGET_ESTIME NUMBER(12,2) NOT NULL,
    RISQUE NUMBER(5,2),
    COUVERTURE_JOURS NUMBER(10,2),
    STRATEGIE VARCHAR2(50),
    UTILISATEUR VARCHAR2(100) DEFAULT USER,
    STATUT VARCHAR2(50) DEFAULT 'PLANIFIE',
    CONSTRAINT CHK_STATUT_RAVIT CHECK (STATUT IN ('PLANIFIE', 'COMMANDE', 'RECU', 'ANNULE'))
);

CREATE INDEX IDX_RAVIT_DATE ON RAVITAILLEMENT_LOG(DATE_LOG DESC);
CREATE INDEX IDX_RAVIT_MATIERE ON RAVITAILLEMENT_LOG(MATIERE);
CREATE INDEX IDX_RAVIT_STATUT ON RAVITAILLEMENT_LOG(STATUT);

COMMENT ON TABLE RAVITAILLEMENT_LOG IS 'Historique des décisions de ravitaillement';

-- Données de test
INSERT INTO RAVITAILLEMENT_LOG (LOG_ID, MATIERE, FOURNISSEUR, SCORE_GLOBAL, QUANTITE_COMMANDE, BUDGET_ESTIME, RISQUE, COUVERTURE_JOURS, STRATEGIE, STATUT)
VALUES ('RAV-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-001', 'Cuir Vachette', 'TanLeather SA', 85.50, 100.00, 4500.00, 15.00, 7.50, 'Equilibre', 'PLANIFIE');

INSERT INTO RAVITAILLEMENT_LOG (LOG_ID, MATIERE, FOURNISSEUR, SCORE_GLOBAL, QUANTITE_COMMANDE, BUDGET_ESTIME, RISQUE, COUVERTURE_JOURS, STRATEGIE, STATUT)
VALUES ('RAV-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-002', 'Cuir Agneau', 'SoftHide Pro', 92.00, 50.00, 2600.00, 8.00, 10.00, 'Qualite', 'COMMANDE');

COMMIT;
PROMPT ✓ Table RAVITAILLEMENT_LOG créée avec 2 logs

-- =============================================
-- 5. VUES ET PROCÉDURES
-- =============================================
PROMPT;
PROMPT [5/5] Création vues et procédures...

-- Vue agrégée du stock
CREATE OR REPLACE VIEW V_STOCK_AGREGE AS
SELECT 
    CATEGORIE_MP,
    SUM(QUANTITE) AS QUANTITE_TOTALE,
    COUNT(*) AS NB_LOTS,
    MAX(DATE_MODIFICATION) AS DERNIERE_MAJ,
    AVG(QUANTITE) AS QUANTITE_MOYENNE
FROM MATIERES_PREMIERES
GROUP BY CATEGORIE_MP;

-- Vue fournisseurs actifs
CREATE OR REPLACE VIEW V_FOURNISSEURS_ACTIFS AS
SELECT 
    ID_FOURNISSEUR,
    NOM_FOURNISSEUR,
    TYPE_CUIR,
    PRIX_PAR_M2,
    QUALITE,
    DELAI_JOURS,
    STOCK_DISPO,
    EMAIL,
    TELEPHONE
FROM FOURNISSEURS
WHERE ACTIF = '1'
ORDER BY TYPE_CUIR, PRIX_PAR_M2;

-- Vue analyse ravitaillement
CREATE OR REPLACE VIEW V_ANALYSE_RAVITAILLEMENT AS
SELECT 
    TO_CHAR(DATE_LOG, 'YYYY-MM') AS MOIS,
    MATIERE,
    COUNT(*) AS NB_COMMANDES,
    SUM(QUANTITE_COMMANDE) AS QTE_TOTALE,
    SUM(BUDGET_ESTIME) AS BUDGET_TOTAL,
    AVG(SCORE_GLOBAL) AS SCORE_MOYEN,
    AVG(COUVERTURE_JOURS) AS COUVERTURE_MOYENNE
FROM RAVITAILLEMENT_LOG
GROUP BY TO_CHAR(DATE_LOG, 'YYYY-MM'), MATIERE
ORDER BY MOIS DESC, MATIERE;

-- Procédure: Ajouter matière première
CREATE OR REPLACE PROCEDURE SP_AJOUTER_MATIERE(
    p_code_mp IN VARCHAR2,
    p_categorie IN VARCHAR2,
    p_num_lot IN VARCHAR2,
    p_etat IN VARCHAR2,
    p_couleur IN VARCHAR2,
    p_quantite IN NUMBER,
    p_type_stockage IN VARCHAR2,
    p_qualite IN VARCHAR2
) AS
BEGIN
    INSERT INTO MATIERES_PREMIERES (
        ID_STOCK_MP, CODE_MP, CATEGORIE_MP, NUM_LOT, ETAT_MP,
        COULEUR, QUANTITE, TYPE_STOCKAGE, QUALITE
    ) VALUES (
        SEQ_MAT.NEXTVAL, p_code_mp, p_categorie, p_num_lot, p_etat,
        p_couleur, p_quantite, p_type_stockage, p_qualite
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✓ Matière ajoutée: ' || p_code_mp);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('✗ Erreur: ' || SQLERRM);
        RAISE;
END;
/

-- Procédure: Enregistrer ravitaillement
CREATE OR REPLACE PROCEDURE SP_LOG_RAVITAILLEMENT(
    p_matiere IN VARCHAR2,
    p_fournisseur IN VARCHAR2,
    p_score IN NUMBER,
    p_quantite IN NUMBER,
    p_budget IN NUMBER,
    p_risque IN NUMBER,
    p_couverture IN NUMBER,
    p_strategie IN VARCHAR2
) AS
    v_log_id VARCHAR2(40);
BEGIN
    v_log_id := 'RAV-' || TO_CHAR(SYSDATE, 'YYYYMMDD-HH24MISS');
    
    INSERT INTO RAVITAILLEMENT_LOG (
        LOG_ID, MATIERE, FOURNISSEUR, SCORE_GLOBAL, QUANTITE_COMMANDE,
        BUDGET_ESTIME, RISQUE, COUVERTURE_JOURS, STRATEGIE
    ) VALUES (
        v_log_id, p_matiere, p_fournisseur, p_score, p_quantite,
        p_budget, p_risque, p_couverture, p_strategie
    );
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✓ Ravitaillement enregistré: ' || v_log_id);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('✗ Erreur: ' || SQLERRM);
        RAISE;
END;
/

-- Procédure: Calculer besoin ravitaillement
CREATE OR REPLACE PROCEDURE SP_CALCULER_BESOIN(
    p_categorie IN VARCHAR2,
    p_stock_actuel IN NUMBER,
    p_seuil_securite IN NUMBER,
    p_conso_prevue IN NUMBER,
    p_besoin OUT NUMBER,
    p_couverture OUT NUMBER
) AS
BEGIN
    p_besoin := GREATEST(0, p_seuil_securite + p_conso_prevue - p_stock_actuel);
    p_couverture := p_stock_actuel / GREATEST(0.01, p_conso_prevue / 7.0);
    
    DBMS_OUTPUT.PUT_LINE('Catégorie: ' || p_categorie);
    DBMS_OUTPUT.PUT_LINE('Besoin calculé: ' || TO_CHAR(p_besoin, '999999.99') || ' M²');
    DBMS_OUTPUT.PUT_LINE('Couverture: ' || TO_CHAR(p_couverture, '999.99') || ' jours');
END;
/

PROMPT ✓ Vues et procédures créées

-- =============================================
-- 6. RÉSUMÉ FINAL
-- =============================================
PROMPT;
PROMPT ========================================
PROMPT RÉSUMÉ DE L'INSTALLATION
PROMPT ========================================
PROMPT;

SELECT 'Tables créées' AS TYPE, COUNT(*) AS NOMBRE
FROM user_tables 
WHERE table_name IN ('MATIERES_PREMIERES', 'FOURNISSEURS', 'STOCK_MP', 'RAVITAILLEMENT_LOG')
UNION ALL
SELECT 'Séquences créées', COUNT(*)
FROM user_sequences 
WHERE sequence_name IN ('SEQ_MAT', 'SEQ_FOURNISSEUR', 'SEQ_STOCK_MP')
UNION ALL
SELECT 'Vues créées', COUNT(*)
FROM user_views 
WHERE view_name IN ('V_STOCK_AGREGE', 'V_FOURNISSEURS_ACTIFS', 'V_ANALYSE_RAVITAILLEMENT')
UNION ALL
SELECT 'Procédures créées', COUNT(*)
FROM user_objects 
WHERE object_type = 'PROCEDURE' 
AND object_name IN ('SP_AJOUTER_MATIERE', 'SP_LOG_RAVITAILLEMENT', 'SP_CALCULER_BESOIN');

PROMPT;
PROMPT Données insérées:
SELECT 'MATIERES_PREMIERES' AS TABLE_NAME, COUNT(*) AS NB_LIGNES FROM MATIERES_PREMIERES
UNION ALL
SELECT 'FOURNISSEURS', COUNT(*) FROM FOURNISSEURS
UNION ALL
SELECT 'STOCK_MP', COUNT(*) FROM STOCK_MP
UNION ALL
SELECT 'RAVITAILLEMENT_LOG', COUNT(*) FROM RAVITAILLEMENT_LOG;

PROMPT;
PROMPT ========================================
PROMPT ✓ INSTALLATION TERMINÉE AVEC SUCCÈS!
PROMPT ========================================
PROMPT;
PROMPT Prochaines étapes:
PROMPT 1. Copier les fichiers C++ (matierepremiere.h/.cpp)
PROMPT 2. Compiler l'application
PROMPT 3. Tester les fonctionnalités CRUD
PROMPT 4. Tester le module de ravitaillement
PROMPT;
