-- Cas reels demo Sprint 1
-- Objectif: comparer avant/apres sur une meme commande

-- 1) Jours feries / capacite reduite
MERGE INTO CALENDRIER_PROD t
USING (SELECT DATE '2026-05-01' AS d FROM dual) s
ON (TRUNC(t.DATE_JOUR)=TRUNC(s.d))
WHEN MATCHED THEN UPDATE SET t.EST_OUVRE=0, t.EST_FERIE=1, t.COEFFICIENT_CAPACITE=0, t.COMMENTAIRE='Fete du travail', t.UPDATED_AT=SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_CAL, DATE_JOUR, EST_OUVRE, EST_FERIE, COEFFICIENT_CAPACITE, COMMENTAIRE, UPDATED_AT)
VALUES (NULL, s.d, 0, 1, 0, 'Fete du travail', SYSDATE);

MERGE INTO CALENDRIER_PROD t
USING (SELECT DATE '2026-05-04' AS d FROM dual) s
ON (TRUNC(t.DATE_JOUR)=TRUNC(s.d))
WHEN MATCHED THEN UPDATE SET t.EST_OUVRE=1, t.EST_FERIE=0, t.COEFFICIENT_CAPACITE=0.70, t.COMMENTAIRE='Maintenance atelier', t.UPDATED_AT=SYSDATE
WHEN NOT MATCHED THEN INSERT (ID_CAL, DATE_JOUR, EST_OUVRE, EST_FERIE, COEFFICIENT_CAPACITE, COMMENTAIRE, UPDATED_AT)
VALUES (NULL, s.d, 1, 0, 0.70, 'Maintenance atelier', SYSDATE);

-- 2) 2-3 absences (remplace les IDs par des IDs reels de ta base)
-- Exemple: employes 1,2,3 absents quelques jours
INSERT INTO ABSENCES_EMPLOYES (ID_ABSENCE, ID_EMPLOYE, DATE_DEBUT, DATE_FIN, TYPE_ABSENCE, COMMENTAIRE, CREATED_AT)
VALUES (NULL, 1, DATE '2026-05-05', DATE '2026-05-06', 'CONGE', 'Conge annuel', SYSDATE);

INSERT INTO ABSENCES_EMPLOYES (ID_ABSENCE, ID_EMPLOYE, DATE_DEBUT, DATE_FIN, TYPE_ABSENCE, COMMENTAIRE, CREATED_AT)
VALUES (NULL, 2, DATE '2026-05-07', DATE '2026-05-07', 'MALADIE', 'Arret 1 jour', SYSDATE);

INSERT INTO ABSENCES_EMPLOYES (ID_ABSENCE, ID_EMPLOYE, DATE_DEBUT, DATE_FIN, TYPE_ABSENCE, COMMENTAIRE, CREATED_AT)
VALUES (NULL, 3, DATE '2026-05-08', DATE '2026-05-09', 'FORMATION', 'Formation externe', SYSDATE);

COMMIT;

-- 3) Check rapide
SELECT COUNT(*) AS nb_cal FROM CALENDRIER_PROD;
SELECT COUNT(*) AS nb_abs FROM ABSENCES_EMPLOYES;
