-- Sprint 3 - IA Decoupe
-- Migration schema: contraintes metier par piece
-- Cible: PROJET_CPP.PRODUIT_PIECES

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  ADD (
    ZONE_PREFEREE   VARCHAR2(20),
    SENS_GRAIN      NUMBER(1),
    NIVEAU_QUALITE  NUMBER(1)
  );

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  MODIFY (ZONE_PREFEREE DEFAULT 'COLLET');

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  MODIFY (SENS_GRAIN DEFAULT 0);

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  MODIFY (NIVEAU_QUALITE DEFAULT 1);

UPDATE PROJET_CPP.PRODUIT_PIECES
SET ZONE_PREFEREE = NVL(ZONE_PREFEREE, 'COLLET'),
    SENS_GRAIN = NVL(SENS_GRAIN, 0),
    NIVEAU_QUALITE = NVL(NIVEAU_QUALITE, 1);

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  MODIFY (ZONE_PREFEREE NOT NULL);

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  MODIFY (SENS_GRAIN NOT NULL);

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  MODIFY (NIVEAU_QUALITE NOT NULL);

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  ADD CONSTRAINT CK_PP_ZONE_PREF
  CHECK (ZONE_PREFEREE IN ('DOSSET','CROUPON','FLANC','COLLET'));

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  ADD CONSTRAINT CK_PP_SENS_GRAIN
  CHECK (SENS_GRAIN IN (0,1,2));

ALTER TABLE PROJET_CPP.PRODUIT_PIECES
  ADD CONSTRAINT CK_PP_NIVEAU_QUALITE
  CHECK (NIVEAU_QUALITE IN (1,2,3));

COMMIT;
