-- Sprint 2 - Competences par etape (compatibilite Oracle large)

CREATE TABLE COMPETENCES_EMPLOYES (
    ID_COMPETENCE NUMBER PRIMARY KEY,
    ID_EMPLOYE NUMBER NOT NULL,
    ETAPE VARCHAR2(40) NOT NULL,
    NIVEAU NUMBER(2) DEFAULT 1 NOT NULL,
    ACTIF NUMBER(1) DEFAULT 1 NOT NULL,
    COMMENTAIRE VARCHAR2(200),
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_COMP_EMP FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYES(ID_EMPLOYE),
    CONSTRAINT CK_COMP_NIV CHECK (NIVEAU BETWEEN 1 AND 5),
    CONSTRAINT CK_COMP_ACTIF CHECK (ACTIF IN (0, 1)),
    CONSTRAINT UK_COMP_EMP_ETAPE UNIQUE (ID_EMPLOYE, ETAPE)
);

CREATE SEQUENCE SEQ_COMPETENCES_EMPLOYES START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_COMPETENCES_EMPLOYES_BI
BEFORE INSERT ON COMPETENCES_EMPLOYES
FOR EACH ROW
BEGIN
    IF :NEW.ID_COMPETENCE IS NULL THEN
        :NEW.ID_COMPETENCE := SEQ_COMPETENCES_EMPLOYES.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_COMP_EMP_ETAPE ON COMPETENCES_EMPLOYES (ID_EMPLOYE, ETAPE);
CREATE INDEX IDX_COMP_ETAPE ON COMPETENCES_EMPLOYES (ETAPE);

-- Exemple de jeu de donnees (adapte ensuite les IDs employes selon ta base):
-- INSERT INTO COMPETENCES_EMPLOYES (ID_EMPLOYE, ETAPE, NIVEAU, ACTIF, COMMENTAIRE)
-- VALUES (1, 'COUPE', 4, 1, 'Expert coupe');
-- INSERT INTO COMPETENCES_EMPLOYES (ID_EMPLOYE, ETAPE, NIVEAU, ACTIF)
-- VALUES (1, 'ASSEMBLAGE', 3, 1);
-- INSERT INTO COMPETENCES_EMPLOYES (ID_EMPLOYE, ETAPE, NIVEAU, ACTIF)
-- VALUES (2, 'COUTURE', 5, 1);
-- INSERT INTO COMPETENCES_EMPLOYES (ID_EMPLOYE, ETAPE, NIVEAU, ACTIF)
-- VALUES (3, 'FINITION', 4, 1);
-- COMMIT;
