-- Sprint 1 V2 - Calendrier reel, absences, capacite variable
-- Oracle SQL (compatibilite large via SEQUENCE + TRIGGER)

-- 1) CALENDRIER_PROD
CREATE TABLE CALENDRIER_PROD (
    ID_CAL NUMBER PRIMARY KEY,
    DATE_JOUR DATE NOT NULL,
    EST_OUVRE NUMBER(1) DEFAULT 1 NOT NULL,
    EST_FERIE NUMBER(1) DEFAULT 0 NOT NULL,
    COEFFICIENT_CAPACITE NUMBER(4,2) DEFAULT 1 NOT NULL,
    COMMENTAIRE VARCHAR2(200),
    UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT UK_CALENDRIER_PROD_DATE UNIQUE (DATE_JOUR),
    CONSTRAINT CK_CALENDRIER_OUVRE CHECK (EST_OUVRE IN (0, 1)),
    CONSTRAINT CK_CALENDRIER_FERIE CHECK (EST_FERIE IN (0, 1)),
    CONSTRAINT CK_CALENDRIER_COEF CHECK (COEFFICIENT_CAPACITE >= 0 AND COEFFICIENT_CAPACITE <= 2)
);

CREATE SEQUENCE SEQ_CALENDRIER_PROD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_CALENDRIER_PROD_BI
BEFORE INSERT ON CALENDRIER_PROD
FOR EACH ROW
BEGIN
    IF :NEW.ID_CAL IS NULL THEN
        :NEW.ID_CAL := SEQ_CALENDRIER_PROD.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_CALENDRIER_PROD_DATE ON CALENDRIER_PROD (DATE_JOUR);

-- 2) ABSENCES_EMPLOYES
CREATE TABLE ABSENCES_EMPLOYES (
    ID_ABSENCE NUMBER PRIMARY KEY,
    ID_EMPLOYE NUMBER NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL,
    TYPE_ABSENCE VARCHAR2(40) DEFAULT 'ABSENCE' NOT NULL,
    COMMENTAIRE VARCHAR2(200),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_ABS_EMP FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYES(ID_EMPLOYE),
    CONSTRAINT CK_ABS_DATES CHECK (DATE_FIN >= DATE_DEBUT)
);

CREATE SEQUENCE SEQ_ABSENCES_EMPLOYES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_ABSENCES_EMPLOYES_BI
BEFORE INSERT ON ABSENCES_EMPLOYES
FOR EACH ROW
BEGIN
    IF :NEW.ID_ABSENCE IS NULL THEN
        :NEW.ID_ABSENCE := SEQ_ABSENCES_EMPLOYES.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_ABS_EMP_DATES ON ABSENCES_EMPLOYES (ID_EMPLOYE, DATE_DEBUT, DATE_FIN);
CREATE INDEX IDX_ABS_DATE_RANGE ON ABSENCES_EMPLOYES (DATE_DEBUT, DATE_FIN);

-- 3) CAPACITE_POSTE_JOUR
CREATE TABLE CAPACITE_POSTE_JOUR (
    ID_CAPA NUMBER PRIMARY KEY,
    DATE_JOUR DATE NOT NULL,
    ETAPE VARCHAR2(40) NOT NULL,
    HEURES_DISPONIBLES NUMBER(6,2) NOT NULL,
    RENDEMENT NUMBER(4,2) DEFAULT 1 NOT NULL,
    COMMENTAIRE VARCHAR2(200),
    CONSTRAINT UK_CAP_POSTE_JOUR UNIQUE (DATE_JOUR, ETAPE),
    CONSTRAINT CK_CAP_HOURS CHECK (HEURES_DISPONIBLES > 0 AND HEURES_DISPONIBLES <= 24),
    CONSTRAINT CK_CAP_REND CHECK (RENDEMENT > 0 AND RENDEMENT <= 1.5)
);

CREATE SEQUENCE SEQ_CAPACITE_POSTE_JOUR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE OR REPLACE TRIGGER TRG_CAPACITE_POSTE_JOUR_BI
BEFORE INSERT ON CAPACITE_POSTE_JOUR
FOR EACH ROW
BEGIN
    IF :NEW.ID_CAPA IS NULL THEN
        :NEW.ID_CAPA := SEQ_CAPACITE_POSTE_JOUR.NEXTVAL;
    END IF;
END;
/

CREATE INDEX IDX_CAP_POSTE_DATE ON CAPACITE_POSTE_JOUR (DATE_JOUR);
CREATE INDEX IDX_CAP_POSTE_ETAPE ON CAPACITE_POSTE_JOUR (ETAPE);

-- 4) Donnees exemples minimales (optionnel)
INSERT INTO CALENDRIER_PROD (DATE_JOUR, EST_OUVRE, EST_FERIE, COEFFICIENT_CAPACITE, COMMENTAIRE)
VALUES (DATE '2026-05-01', 0, 1, 0, 'Fete du travail');

INSERT INTO CALENDRIER_PROD (DATE_JOUR, EST_OUVRE, EST_FERIE, COEFFICIENT_CAPACITE, COMMENTAIRE)
VALUES (DATE '2026-05-08', 0, 1, 0, 'Jour ferie');

COMMIT;
